export const actionTypes = {
    LOGIN:'Login',
    SIGN_UP:'SignUp',
    SOCIAL_LOGIN: 'SocialLogin',
    USER_DATA:'UserData',
    ACCESS_TOKEN:'AccessToken',
    SET_ADVERTISMENTS:'SetAdvertisements',
    MINIMIZE_PLAYER:'MinimizePlayer',
    CHANGE_PLAYLIST:'ChangePlaylist',
    SET_PLAY_COUNT:'PlayCount',
    UPDATE_TRACK_INDEX:'UpdateTrackIndex',
    LOGOUT_USER:'LogoutUser',
    CHANGE_PLAYER_STATE:'ChangePlayerState',
    ADD_SONG_TO_QUEUE:'AddSongToQueue',
    SET_LIKED_SONGS:'SetLikedSongs',
    LIKE_UNLIKE_SONG:'LikeUnlikeSong',
    PLAY_PAUSE_PODCAST:'PlayPausePodcast',
    SET_LIKED_PODCASTS:'SetLikedPodcasts',
    LIKE_UNLIKE_PODCAST:'LikeUnlikePodcast',
    SET_USER_SETTINGS:'SetUserSettings',
    EXTEND_PLAYLIST:'ExtendPlaylist',
    TOGGLE_SHUFFLE:'ToggleShuffle',
    TOGGLE_REPEAT_MODE:'ToggleRepeatMode',
    SET_CURRENT_INTERNET_STATUS:'SetCurrentInternetStatus',
    SET_DOWNLOADED_SONGS:'SetDownloadedSongs',
    ADD_DOWNLOADED_SONG:'AddDownloadedSong',
    REMOVE_DOWNLOADED_SONG:'RemoveDownloadedSong'
}