export const imagePath = {
    mapIcon: require('../images/map.png'),
    backIcon: require('../images/back.png'),
    profileIcon: require('../images/Icon.png'),
    mailIcon: require('../images/Mail.png'),
    lockIcon: require('../images/Lock.png'),
    facebookIcon: require('../images/facebook.png'),
    googleIcon: require('../images/google.png'),
    appleIcon: require('../images/apple.png'),
    checkedRadioIcon: require('../images/CheckedRadio.png'),
    uncheckedRadioIcon: require('../images/UncheckedRadio.png'),
    nextIcon: require('../images/nextIcon.png'),
    threeDotsIcon: require('../images/threeDots.png'),
    dropdownIcon: require('../images/dropdownIcon.png'),
    connectionUnavailable: require('../images/connectionUnavailable.png'),
    addIcon: require('../images/addIcon.png'),
    dummySong: require('../images/dummySong.png'),
    dummyArtist: require('../images/dummyArtist.png'),
    artist1: require('../images/dummyArtist1.jpg'),
    artist2: require('../images/dummyArtist2.jpg'),
    artist3: require('../images/dummyArtist3.jpg'),
    heart: require('../images/heart.png'),
    download: require('../images/download.png'),
}